export const STORES = {
  FETCH_ALL_STORES_REQUEST: 'FETCH_ALL_STORES_REQUEST',
  FETCH_ALL_STORES_SUCCESS: 'FETCH_ALL_STORES_SUCCESS',
  FETCH_ALL_STORES_FAILURE: 'FETCH_ALL_STORES_FAILURE',

  FETCH_STORE_BY_ID_REQUEST: 'FETCH_STORE_BY_ID_REQUEST',
  FETCH_STORE_BY_ID_SUCCESS: 'FETCH_STORE_BY_ID_SUCCESS',
  FETCH_STORE_BY_ID_FAILURE: 'FETCH_STORE_BY_ID_FAILURE',

  UPDATE_STORE_BY_ID_REQUEST: 'UPDATE_STORE_BY_ID_REQUEST',
  UPDATE_STORE_BY_ID_SUCCESS: 'UPDATE_STORE_BY_ID_SUCCESS',
  UPDATE_STORE_BY_ID_FAILURE: 'UPDATE_STORE_BY_ID_FAILURE'
};

export const RED_INVOICES = {
  FETCH_RED_INVOICE_BY_ID_REQUEST: 'FETCH_RED_INVOICE_BY_ID_REQUEST',
  FETCH_RED_INVOICE_BY_ID_SUCCESS: 'FETCH_RED_INVOICE_BY_ID_SUCCESS',
  FETCH_RED_INVOICE_BY_ID_FAILURE: 'FETCH_RED_INVOICE_BY_ID_FAILURE',

  UPDATE_RED_INVOICE_BY_ID_REQUEST: 'UPDATE_RED_INVOICE_BY_ID_REQUEST',
  UPDATE_RED_INVOICE_BY_ID_SUCCESS: 'UPDATE_RED_INVOICE_BY_ID_SUCCESS',
  UPDATE_RED_INVOICE_BY_ID_FAILURE: 'UPDATE_RED_INVOICE_BY_ID_FAILURE'
};
